### ISSUE TITLE
你是怎样的穷屌丝？

### ISSUE THREAD

**Issue by andandroidor** [iviviviviviv/freeNodes#2]
滚你妈的 sb

**Comment by iviviviviviv** [comment]
> 滚你妈的 sb

我是不敢软件收费但是快饿死了于是把基础功能做成付费最后被一堆人骂的关闭issue再跑到用户页面来喷粪的sb穷屌丝

**Comment by andandroidor** [comment]
你这么有能力你自己去做个基础功能啊    爱用不用 没人求你 你也不是pm 

你也不是pm   算个什么玩意儿   巨婴一个   这个世界好像人人欠你似的 ！ 

一堆人?就你一个sb

**Comment by iviviviviviv** [comment]
> 你这么有能力你自己去做个基础功能啊 爱用不用 没人求你 你也不是pm
> 
> 你也不是pm 算个什么玩意儿 巨婴一个 这个世界好像人人欠你似的 ！
> 
> 一堆人?就你一个sb

呦呦呦，你这么理直气壮怎么不敢开issue？怎么把版本介绍里99块3年换台给删了？大龄失业就去马路上要饭吧，那个还有尊严点，爱你呦～

**Comment by andandroidor** [comment]
开不开还不是我的自由  跟敢不敢有什么关系？不开还不是懒得你这种巨婴脏了我的页面

巨婴总会用胆量来衡量别人的行为。

你这狗眼首页readme看不清楚？

爷不偷不抢靠手艺吃饭，用不着巨婴指条出路，尊严更用不着你这巨婴给

倒是世界不围绕巨婴转一不顺巨婴的意，巨婴就狺狺狂吠。

**Comment by andandroidor** [comment]
当婊子还立牌坊 是说 免费又收费么？？？

使用OurTV看电视过程的确免费啊！
功能收费怎么了，吃相难看忍着，又没吃你家粮食了

有大大方方收费的赶紧去用吧：
![image](https://github.com/user-attachments/assets/0d4c09f4-a650-42bb-a010-eb17dc1df682)
